### ISSUE TITLE
is able to force webSocket transport?

### ISSUE THREAD

**Issue by orvice** [infitio/flutter_socket_io#24]

**Comment by tiholic** [comment]
@orvice can you elaborate!

**Comment by lhcdims** [comment]
When we use your package to connect to a socket.io server, we can use the socket.conn.transport.name on the server side to check the transport type, and the transport type is always 'pooling', so the question is, how can we connect the socket.io server by 'websocket' instead of 'pooling'?

I tried to force transport type to 'websocket' by using:

```
transports: ['websocket'],
```

on the socket.io server, but the socket.connect() will always fail.

**Comment by tiholic** [comment]
@lhcdims Custom options to configure transports is developed for Android in https://github.com/infitio/flutter_socket_io/commit/18031507364dfb760a4d4b8765544061c082884d

It would be great if you can handle the same for iOS

**Comment by tiholic** [comment]
@orvice @lhcdims iOS support is published in 0.3.1

Leaving this issue open for until Android support is developed

**Comment by tiholic** [comment]
Support added for all platforms, please upgrade to latest version (1.0.0)
@orvice @lhcdims
